### ISSUE TITLE
Cannot dynamically create an instance of type array

### ISSUE THREAD

**Issue by rpagyc** [SimplifyNet/Simplify.Web.Postman#31]
Unable to generate postman collection for controller which accepts array of objects in request (ex. AsyncController<RequestViewModel[])

System.MissingMethodException: 'Cannot dynamically create an instance of type 'RequestViewModel[]'. Reason: Type is not supported.'

**Comment by i4004** [comment]
Done via `IList<T>`, should use `IList<RequestViewModel>` instead of arrays.
